# SwiftLint Configuration for Telnyx WebRTC iOS SDK
# Not overly restrictive - focus on code quality and consistency

# Paths to include/exclude
included:
  - TelnyxRTC
  - TelnyxWebRTCDemo
  - TelnyxRTCTests

excluded:
  - Pods
  - TelnyxRTC.xcodeproj
  - TelnyxRTC.xcworkspace
  - fastlane
  - scripts
  - docs
  - docs-markdown
  - push-notification-tool

# Opt-in rules (good practices but not enabled by default)
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - contains_over_first_not_nil
  - multiline_parameters
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules (too restrictive or not applicable)
disabled_rules:
  - trailing_whitespace  # Can be handled by editor auto-format
  - function_parameter_count  # SDK methods may need many parameters
  - type_body_length  # Some SDK classes are legitimately large
  - file_length  # Some files are large by necessity
  - cyclomatic_complexity  # Can be overly restrictive for SDK code
  - nesting  # Delegate implementations may require nesting

# Line length with generous limits
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 60
  error: 100

# Type name rules
type_name:
  min_length: 3
  max_length: 50
  
# Identifier name rules  
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - to
    - tx
    - rx

# Force cast - warning only (SDK may need these occasionally)
force_cast: warning

# Trailing comma
trailing_comma:
  mandatory_comma: true

# Reporter
reporter: "xcode"
