# Fastlane runs swiftlint from one directory above where the Fastfile lives 
# so make sure all the paths are relative in that regard.

# Find all the available rules by running:
# swiftlint rules

opt_in_rules: 

included:
  - ../TelnyxRTC
  - ../TelnyxRTC Tests
  - ../TelnyxWebRTCDemo

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - build
  - dist

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length: 
  warning: 250
  error: 400

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 1000
  error: 1500

# reporter type (xcode, json, csv, checkstyle)
reporter: "xcode"

- name: Setup Xcode version
  uses: maxim-lobanov/setup-xcode@v1.5.1

